Log:
  Level: none
  AccessPath: 
  ErrorPath: 
DnsConfigPath: 
RouteConfigPath: /etc/XrayR/route.json
InboundConfigPath:
OutboundConfigPath: /etc/XrayR/custom_outbound.json
ConnectionConfig:
  Handshake: 4 
  ConnIdle: 10
  UplinkOnly: 2 
  DownlinkOnly: 4 
  BufferSize: 64 
Nodes:
  -
    PanelType: "NewV2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: "https://cdn.bocchi.ooo"
      ApiKey: "miaopasimiaopasimiaopasi"
      NodeID: 1
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type, Prefer remote configuration
      EnableXTLS: false # Enable XTLS for V2ray and Trojan， Prefer remote configuration
      SpeedLimit: 0 
      DeviceLimit: 0 
      RuleListPath:
